[project]
name = "sclass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "django>=4.2.20",
    "psycopg>=3.2.6",
    "psycopg2>=2.9.10",
]
