# Generated by Django 5.1.7 on 2025-05-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todolist', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("""
                    CREATE TABLE todo_list (
                        id serial primary key,
                        title varchar(255) NOT NULL,
                        deadline date NOT NULL,
                        detail text NOT NULL,
                        created_at date default now()
                    );
                """)
            ], 
            
            reverse_sql=[
                ("""
                    drop table if exists todo_list;
                """)
            ])
    ]
